# running dengan cara
# docker-compose -f docker-compose.yml up -d  => -d == daemon/berjalan di background
# cek : docker container ls
# docker container logs kotlin-restful-api-postgres
version: '3.5'  # version docker compose

services:
  kotlin-restful-api:           # container information app rest api kotlin
    container_name: kotlin-restful-api
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restful-api

  kotlin-restful-api-postgres:  # container information postgres
    container_name: "kotlin-restful-api-postgres"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restful-api
      # using volumes in postgres
    volumes:
     - postgres_db:/var/lib/postgresql/data   # where store data postgres
     #- ./postgres_db:/var/lib/postgresql/data   # where store data postgres -> in directory postgres_db if you want backup folder db
# using volumes in postgres
volumes:
  postgres_db: {}